---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-secret
  namespace: guide-helper
spec:
  encryptedData:
    .dockerconfigjson: AgBJ05FdPRshBn6pxlU2S+T5Muz3mNIrS7WMAR0kLM/spemoQoZbzNQ1CEGDP9sJoBuJSu0qNsiTjwVMk4Pf5CLfkkoGsCIegfwAQI9w2wSLf79Ba8kkMFlrDvOEHK9FxnzqTTs5pefOHraQ1nbsMCEJceMJHVU8GJmQBeqxtGn5T5SNHpuxlqo01eqMKDLajgoW+BaQRORBGbc712BnGiOyogPE3KZYJV19V/a5aAftDpb+mGx9Sy3ml/CZCqxdhrGutAKtkLkOu1O3+fuGHPyiefa7BSm2Mgp5RCJROJN9gG7zdElvnTktMV5t90JcY6+1oTBYvlOoh9b25Fd0e6kvS1AOwgQkSlM+Pm2urZnHeVJGYF8y5akqFl6lmgZm8u9M/LitouIPi33GtMzpja7JEx01LFKf43fsRHD6tXtrarkZsac153Vh91Le20xfUPIRInSCNBBSidMbSGv9PXm3IpJO88H5ftxSxiLQy3zcJucyYkhsHopv/Fmoit6xvhz7nuV1BIxFRyIjAzUnfezwkFS/2CKI7FMvYEqBKNxnSNE/4FZ2PAf/rhmDWobz9eKq6ZVP6GzTxG5M5AZgKl8WqkZw3BKDZZIg59NuCg2uKutSDQGew4LUqzaiEzMDLfQfwve8UsO0iHq0TRHLqdWzxRgRe34OvLFBbEITkxmK1BhCg86j1c+JC1SS+2wIn/iZQFGJbMEXdLxMaEmgUh2JESh/D+oQ7OJteEGSWDFsfFMCtha2BqE+kV37wlbtQ8/8bd08/pnFl568c5cURH9oF+hz7bwJiQo+3k4bE6TAxVvb+rBfd39gbwqMC2Af5EEoJauKu38x0zukS1S2KvNtCtvzRCmJ0sFCEm1ho2nrU0Tq1vvDE9G7ifOnxMWc/+Q8i1zhmzcQb+degb8bfu1WsEqKtb7rfNdwZIo3
  template:
    metadata:
      name: ghcr-secret
      namespace: guide-helper
    type: kubernetes.io/dockerconfigjson
